@startwbs
* Hauptmenü
** Hintergrundbild
** Auswahl
*** Medikamentehinzufügen (sub)
**** Medikamentehinzufügen (Windows/View)
*** Medikamenteentfernen (sub)
**** Medikamenteentfernen (Windows/View)
** Datum/Uhrzeit (sub)
*** Datum/Uhrzeit (Windows/View)
** Sound (Sub)
** Settings (Menu)
*** Auflösung
*** Color
@endwbs